# This is a basic workflow to help you get started with Actions

name: CI + Ping Vercel

on:
  # CI triggers
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Manual run
  workflow_dispatch:

  # Auto ping schedule (setiap 5 minit)
  schedule:
    - cron: "*/5 * * * *"

jobs:
  # Job CI asal
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Job baru untuk ping vercel
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping utama
        run: |
          echo "Pinging Vercel site..."
          curl -s -o /dev/null -w "%{http_code}" --retry 3 --max-time 10 https://your-vercel-app.vercel.app/ | grep 200
