name: Keep Vercel Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # ping setiap 5 minit
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping utama
        run: |
          curl -s --retry 3 --max-time 10 https://your-vercel-app.vercel.app/ > /dev/null
